name: TODO Finder

on:
  push:
    branches: [main, master] # Run on merges to main/master branches
  pull_request:
    types: [closed] # Also run when PRs are merged
    branches: [main, master]

jobs:
  find-todos:
    name: Find TODOs in codebase
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.merged == true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Debug file listing
        run: |
          echo "Listing top-level directories:"
          ls -la

          echo "Listing some source files:"
          find . -type f -name "*.js" -o -name "*.ts" | head -n 5

      - name: Find TODOs
        id: find-todos
        run: |
          # Create a temporary file for the results
          touch todo_results.txt

          echo "## TODO Finder Results" | tee -a todo_results.txt
          echo "-------------------" | tee -a todo_results.txt

          # Make sure grep doesn't fail on binary files or other issues
          # Use -I to ignore binary files
          # Use || true to ensure the command doesn't fail the workflow
          echo "Searching for TODOs in text files only..."
          TODOS=$(find . -type f -not -path "*/node_modules/*" -not -path "*/.git/*" -not -path "*/dist/*" -not -path "*/build/*" -not -path "*/vendor/*" -exec grep -l -I "TODO" {} \; || true)

          if [ -z "$TODOS" ]; then
            echo "No TODO strings found in initial search. Checking file types..." | tee -a todo_results.txt
            
            # List some file types to verify what we have
            echo "File types in repository:" | tee -a todo_results.txt
            find . -type f -name "*.*" | grep -o "\.[^\.]*$" | sort | uniq -c | sort -nr | head -n 10 | tee -a todo_results.txt
          else
            echo "Found files containing 'TODO':" | tee -a todo_results.txt
            echo "$TODOS" | tee -a todo_results.txt
            
            echo "Details of TODOs found:" | tee -a todo_results.txt
            for file in $TODOS; do
              if [ -f "$file" ]; then
                # Use -n to show line numbers and -I to ignore binary files
                grep -n -I "TODO" "$file" | tee -a todo_results.txt
              fi
            done
          fi

          # Count total TODOs found
          TODO_COUNT=$(echo "$TODOS" | wc -l)

          if [ $TODO_COUNT -gt 0 ]; then
            echo "::notice title=TODOs Found::Found $TODO_COUNT files containing TODOs in your codebase."
          else
            echo "::notice title=No TODOs::No TODOs found in your codebase."
          fi

          # Export the results for PR comments
          echo "$TODO_COUNT" > todo_count.txt

      - name: Comment on PR
        if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const todoResults = fs.readFileSync('todo_results.txt', 'utf8');
            const todoCount = parseInt(fs.readFileSync('todo_count.txt', 'utf8'));

            let commentBody = `## TODO Finder Results\n\n`;

            if (todoCount > 0) {
              commentBody += `Found ${todoCount} files containing TODOs in the codebase.\n\n`;
              commentBody += todoResults;
            } else {
              commentBody += `✅ No TODOs found in the codebase! Great job keeping technical debt in check.`;
            }

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            });
